index:
    path: /
    defaults: { _controller: 'App\Controller\DefaultController::index' }

lucky_number:
    path: /lucky/number
    defaults: { _controller: 'App\Controller\LuckyController::numberAction' }

blog_list_twig:
    path:     /blogtwig
    defaults: { _controller: 'App\Controller\BlogControllerTwig::list' }

blog_show_twig:
    path:     /blogtwig/{entryId}
    defaults: { _controller: 'App\Controller\BlogControllerTwig::show' }
